SELECT USER_ID, USERNAME, CREATED, PASSWORD_CHANGE_DATE FROM USER_USERS;

SELECT * FROM USER_TABLES;

SELECT * FROM ORDERS;
SELECT * FROM PRODUCTLIST;
SELECT * FROM REVIEWS;
SELECT * FROM STOREFRONT;
SELECT * FROM USERBASE;
SELECT * FROM USERLIBRARY;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS FROM USER_CONSTRAINTS;

SELECT VIEW_NAME, TEXT FROM USER_VIEWS;

SELECT USERNAME FROM USERBASE ORDER BY USERNAME;

SELECT FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL
FROM USERBASE
WHERE EMAIL LIKE '%@yahoo.com';

SELECT USERNAME, BIRTHDAY, WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS < 25;

SELECT USERID, PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED > 100;

SELECT PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED < 10;

SELECT DISTINCT PUBLISHER
FROM PRODUCTLIST;

SELECT PRODUCTNAME, RELEASEDATE, PUBLISHER, GENRE
FROM PRODUCTLIST
ORDER BY GENRE;

SELECT PRODUCTCODE, PUBLISHER
FROM PRODUCTLIST
WHERE GENRE = 'Strategy';

SELECT PRODUCTCODE, DESCRIPTION, PRICE
FROM STOREFRONT
WHERE PRICE > 25
ORDER BY PRICE DESC;

SELECT INVENTORYID, PRICE
FROM STOREFRONT
ORDER BY PRICE ASC;

SELECT PRODUCTCODE, REVIEW
FROM REVIEWS
WHERE RATING = 1;

SELECT PRODUCTCODE, REVIEW
FROM REVIEWS
WHERE RATING >= 4;

SELECT DISTINCT USERID
FROM ORDERS;

SELECT *
FROM ORDERS
ORDER BY PURCHASEDATE;
